apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alert-service.fullname" . }}-secrets
  labels:
    {{- include "alert-service.labels" . | nindent 4 }}
type: Opaque
data:
  db-username: {{ .Values.secrets.dbUsername | b64enc | quote }}
  db-password: {{ .Values.secrets.dbPassword | b64enc | quote }}
